<a href="https://colab.research.google.com/github/Tsatthienmach/AiSummerCode/blob/master/week5/numpy_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lay phan tu chung

In [0]:
import numpy as np

In [0]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print("adarray1 and 2")
print(arr1)
print(arr2)

out = np.intersect1d(arr1  , arr2)
print('\nout ' , out)

adarray1 and 2
[1 2 3 4 5]
[3 4 5 6 7]

out  [3 4 5]


# Từ mảng arr1 xóa  tất cả các phần tử mà có trong mảng arr2

In [0]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([3,5,7,9])
out = np.setdiff1d(arr1 , arr2)
print(out)

[2 4]


# Lấy các phần tử giống nhau trong 2 mảng

In [0]:
arr1 = np.array([3, 4, 5, 6, 7, 8])
arr2 = np.array([2, 3, 6, 6, 7, 7])

In [11]:
index  = np.where(arr1 == arr2)
print(index)

(array([3, 4]),)


In [0]:
print(out)

# Tìm giá trị max giữa 2 mảng

In [0]:
arr1 = np.array([3, 4, 5, 6, 7, 8])
arr2 = np.array([3, 3, 6, 6, 7, 7])

In [14]:
# Cach 1:
def max_value(x,y):
    if x>= y :
        return x
    else:
        return y 

pair_max = np.vectorize(max_value , otypes=[float])
out1 = pair_max(arr1 , arr2)
print(out1 , end = ' ')


[3. 4. 6. 6. 7. 8.] 

In [16]:
out2 = np.maximum(arr1 , arr2)
print(out2 , end = ' ')

[3 4 6 6 7 8] 

In [17]:
out3 = np.where(arr1 > arr2 , arr1 , arr2)
print(out3)

[3 4 6 6 7 8]


# Hoán đổi vị trí 2 cột

In [18]:
arr = np.arange(12).reshape(4,3)
print(arr , end = '\n\n')
out = arr[:, [1,0,2]]
print(out)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


# Đảo ngược các dòng

In [19]:
out = arr[:,::-1]
print(out)

[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


# Sinh ra mảng 2x3 với các số ngẫu nhiên từ 1-9 ,

In [20]:
arr  =  np.random.uniform(1,9, size = (2,3))
print(arr)

[[7.94584501 8.10128885 8.87775637]
 [3.30065551 8.65519452 1.2495228 ]]


In [22]:
arr = np.random.random([2,3])
print(arr)
np.set_printoptions(precision=2)
print(arr)

[[0.14 0.7  0.29]
 [0.04 0.76 0.93]]
[[0.14 0.7  0.29]
 [0.04 0.76 0.93]]
