<a href="https://colab.research.google.com/github/Tsatthienmach/AiSummerCode/blob/master/week5/numpy_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Clone the entire repo.
!git clone -l -s https://github.com/Tsatthienmach/AiSummerCode.git cloned-repo
%cd cloned-repo
!ls

Cloning into 'cloned-repo'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 110 (delta 46), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (110/110), 1.70 MiB | 10.92 MiB/s, done.
Resolving deltas: 100% (46/46), done.
/content/cloned-repo
_config.yml  documentations  README.md	week2  week4  week5


In [0]:
import numpy as np
path = '/content/cloned-repo/week5/iris.csv'

In [3]:
iris = np.genfromtxt('/content/cloned-repo/week5/iris.csv' , delimiter= ',' , dtype= 'object' )
print(iris.shape)

(30, 5)


In [4]:
iris_1d = np.genfromtxt('/content/cloned-repo/week5/iris.csv' , delimiter= ',' , dtype= None )
print(iris_1d.shape)

(30,)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [5]:
print(iris_1d)

[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, b'Iris-setosa') (5.4, 3.9, 1.7, 0.4, b'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, b'Iris-setosa') (5. , 3.4, 1.5, 0.2, b'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, b'Iris-setosa') (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')
 (7. , 3.2, 4.7, 1.4, b'Iris-versicolor')
 (6.4, 3.2, 4.5, 1.5, b'Iris-versicolor')
 (6.9, 3.1, 4.9, 1.5, b'Iris-versicolor')
 (5.5, 2.3, 4. , 1.3, b'Iris-versicolor')
 (6.5, 2.8, 4.6, 1.5, b'Iris-versicolor')
 (5.7, 2.8, 4.5, 1.3, b'Iris-versicolor')
 (6.3, 3.3, 4.7, 1.6, b'Iris-versicolor')
 (4.9, 2.4, 3.3, 1. , b'Iris-versicolor')
 (6.6, 2.9, 4.6, 1.3, b'Iris-versicolor')
 (5.2, 2.7, 3.9, 1.4, b'Iris-versicolor')
 (6.3, 3.3, 6. , 2.5, b'Iris-virginica')
 (5.8, 2.7, 5.1, 1.9, b'Iris-virginica')
 (7.1, 3. , 5.9, 2.1, b'Iris-virginica')
 (6.3, 2.9, 5.6, 1.8, b'Iris-virginica')
 (6.5, 3. , 5.8, 2.2, b'Iris-virginica')


In [6]:
iris_2d_1 = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d_1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]]


In [7]:
iris_2d_2 = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float' ,  usecols = [0,1,2,3])
print(iris_2d_2)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]]


In [8]:
sepal_length = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float' ,  usecols = [0])
print(sepal_length)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 7.  6.4 6.9 5.5 6.5 5.7 6.3 4.9
 6.6 5.2 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2]


In [9]:
mean , median , std = np.mean(sepal_length) , np.median(sepal_length) , np.std(sepal_length)
print (mean , median , std)

5.843333333333333 5.75 0.947868954843208


# Chuẩn hóa 
### (a-a.min)/(a.max-a.min)

In [0]:
normal_sl = (sepal_length - sepal_length.min())/(sepal_length.max() - sepal_length.min())

In [11]:
print(normal_sl)

[0.21875 0.15625 0.09375 0.0625  0.1875  0.3125  0.0625  0.1875  0.
 0.15625 0.8125  0.625   0.78125 0.34375 0.65625 0.40625 0.59375 0.15625
 0.6875  0.25    0.59375 0.4375  0.84375 0.59375 0.65625 1.      0.15625
 0.90625 0.71875 0.875  ]


# Softmax

In [12]:
def softmax(x):
    e_x = np.exp(x-np.max(x))
    return e_x/e_x.sum()
np.set_printoptions(precision = 4)
print(softmax(sepal_length))

[0.0103 0.0084 0.0069 0.0063 0.0093 0.0139 0.0063 0.0093 0.0051 0.0084
 0.069  0.0379 0.0624 0.0154 0.0418 0.0188 0.0343 0.0084 0.0462 0.0114
 0.0343 0.0208 0.0762 0.0343 0.0418 0.1257 0.0084 0.0931 0.0511 0.0843]


# Missing values , genfromtxt to 2d

In [13]:
iris_2d = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float')
print(iris_2d.shape)

(30, 5)


In [14]:
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]


In [15]:
print('\n Số phần tử là nan: ' , np.isnan(iris_2d).sum())
index = np.where(np.isnan(iris_2d))
print(index)


 Số phần tử là nan:  30
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4]))


# Đọc 4 cột dữ liệu đầu , lọc các dòng có penallength (cột 3) và sepalleng(cột 1) < 50

In [16]:
iris_2d = np.genfromtxt(path , delimiter= ',' , dtype = 'float' ,usecols= [0,1,2,3])
condition = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.)
out = iris_2d[condition]
print(out)

[[4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


#  Mối tương quang giữa cộ thứ 1 và 3 

In [17]:
corr = np.corrcoef(iris_2d[:,0] , iris_2d[:,2])[0,1]
print(corr)

0.8765676654135033


# Tìm giá trị duy nhaasrt và count chúng col species


In [18]:
out , count = np.unique(iris[:,4] , return_counts= True)
print(out)
print(count)

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
[10 10 10]


# Chuyển đổi cột 3 pental_length thành
<-3 small

3->5 medium

->5 large


In [0]:
# hàm np.digitize : trả về vị trí chỉ số của bin mà mỗi phần tử thuộc khoảng bin tương ứng 
# chuyển đổi mảng sang mảng bin tương ứng với bảng định nghĩa chuyển đổi
bin_petal_length = np.digitize(iris[:,2].astype('float') , [0,3,5,10])
# ánh xạ bảng bin thành văn bản tương ứng
label_map = {1: 'small' , 2:'medium' , 3: 'large' , 3:np.nan}
map_bin_petallength = [label_map[x] for x in bin_petal_length]

In [20]:
print(map_bin_petallength)

['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', nan, nan, nan, nan, nan, nan, 'medium', nan, nan, nan]


# Thêm một cột mới = petal + sepel )/2

In [0]:
sepal_length = iris_2d[:,0].astype('float')
petal_length = iris_2d[:,2].astype('float')


In [22]:
new_col = (sepal_length + petal_length)/2
new_col = new_col[:,np.newaxis]
print(new_col.shape , iris_2d.shape)
out = np.hstack((iris_2d , new_col) )
print(out)

(30, 1) (30, 4)
[[5.1  3.5  1.4  0.2  3.25]
 [4.9  3.   1.4  0.2  3.15]
 [4.7  3.2  1.3  0.2  3.  ]
 [4.6  3.1  1.5  0.2  3.05]
 [5.   3.6  1.4  0.2  3.2 ]
 [5.4  3.9  1.7  0.4  3.55]
 [4.6  3.4  1.4  0.3  3.  ]
 [5.   3.4  1.5  0.2  3.25]
 [4.4  2.9  1.4  0.2  2.9 ]
 [4.9  3.1  1.5  0.1  3.2 ]
 [7.   3.2  4.7  1.4  5.85]
 [6.4  3.2  4.5  1.5  5.45]
 [6.9  3.1  4.9  1.5  5.9 ]
 [5.5  2.3  4.   1.3  4.75]
 [6.5  2.8  4.6  1.5  5.55]
 [5.7  2.8  4.5  1.3  5.1 ]
 [6.3  3.3  4.7  1.6  5.5 ]
 [4.9  2.4  3.3  1.   4.1 ]
 [6.6  2.9  4.6  1.3  5.6 ]
 [5.2  2.7  3.9  1.4  4.55]
 [6.3  3.3  6.   2.5  6.15]
 [5.8  2.7  5.1  1.9  5.45]
 [7.1  3.   5.9  2.1  6.5 ]
 [6.3  2.9  5.6  1.8  5.95]
 [6.5  3.   5.8  2.2  6.15]
 [7.6  3.   6.6  2.1  7.1 ]
 [4.9  2.5  4.5  1.7  4.7 ]
 [7.3  2.9  6.3  1.8  6.8 ]
 [6.7  2.5  5.8  1.8  6.25]
 [7.2  3.6  6.1  2.5  6.65]]


#  Lấy mẫu cột spec sao cho số lượng setose gấp đôi versic và virgin

In [0]:
species = iris[:,4]

In [0]:
# Cach 1
label = np.array(['Iris-setosa' , 'Iris-versicolor' ,'Iris-virginca'] )
out1 = np.random.choice(label , 30 , p = [0.5 , 0.25, 0.25])

In [0]:
# Cach 2
probs = np.r_[np.linspace(0,0.500 , num= 10) , np.linspace(0.501 , 0.750 , num=10) ,
              np.linspace(0.751 , 1. , num= 10)]

In [0]:
index = np.searchsorted(probs , np.random.random(30))

In [27]:
out2 = species[index]
print(np.unique(out2 , return_counts= True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([14, 10,  6]))


# Tìm giá trị lớn thứ 2 của petalle trong nhóm setosa

In [28]:
iris = np.genfromtxt(path , delimiter=',' , dtype='object')
print(iris[:10, :])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [31]:
iris_setosa = iris[iris[:,4] == b'Iris-setosa']
print(iris_setosa)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [38]:
petal_length_setosa = iris_setosa[:,2].astype(float)
out = np.unique(np.sort(petal_length_setosa))
print(out[-2])

1.5


# Sắp xếp dữ liệu iris dựa trên sepal_leg

In [40]:
out = iris[iris[:,0].argsort()]
print(out)

[[b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.2' b'2.7' b'3.9' b'1.4' b'Iris-versicolor']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'5.5' b'2.3' b'4.0' b'1.3' b'Iris-versicolor']
 [b'5.7' b'2.8' b'4.5' b'1.3' b'Iris-versicolor']
 [b'5.8' b'2.7' b'5.1' b'1.9' b'Iris-virginica']
 [b'6.3' b'2.9' b'5.6' b'1.8' b'Iris-virginica']
 [b'6.3' b'3.3' b'4.7' b'1.6' b'Iris-versicolor']
 [b'6.3' b'3.3' b'6.0' b'2.5' b'Iris-virginica']
 [b'6.4' b'3.2' b'4.5' b'1.5' b'Iris-versicolor']
 [b'6.5' b'3.0' b'5.8' b'2.2' b'Iris-virgini

# Tìm giá trị xuất hiện nhiều nhất trong cột petal (3) trong tập iris . Lấy các phần tử duy nhất và số lượng mỗi phần tử

In [41]:
values , counts = np.unique(iris[:,2] , return_counts=True)
print(values)
print(counts)

[b'1.3' b'1.4' b'1.5' b'1.7' b'3.3' b'3.9' b'4.0' b'4.5' b'4.6' b'4.7'
 b'4.9' b'5.1' b'5.6' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.6']
[1 5 3 1 1 1 1 3 2 2 1 1 1 2 1 1 1 1 1]


# Tìm vị trí đầu tiền của một giá trị lớn hơn 1.0 trong cột thứ 4

In [42]:
petal_width = iris[:,3].astype(float) > 1.0
print(petal_width)

[False False False False False False False False False False  True  True
  True  True  True  True  True False  True  True  True  True  True  True
  True  True  True  True  True  True]


In [43]:
index = np.argwhere(petal_width)[0]
print(index)

[10]


# Tạo id nhóm dựa trên một biến phần loại cho trước , cột species

In [51]:
species = iris[:,4].astype('str')
# print(species)
# Cách 1
# Vong`loop
output1 = [np.argwhere(np.unique(species) == s).tolist()[0][0]
        for val in np.unique(species)
        for s in species[species == val]]
print(output1)
# Cách 2
output2 =[]
uniqs = np.unique(species)
print(uniqs)
for val in uniqs:
    for s in species[species == val]:
        print(s)
        group_id = np.argwhere(uniqs == s).tolist()[0][0]
        output2.append(group_id) 
print(output2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
