<a href="https://colab.research.google.com/github/Tsatthienmach/AiSummerCode/blob/master/week5/numpy_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Clone the entire repo.
!git clone -l -s https://github.com/Tsatthienmach/AiSummerCode.git cloned-repo
%cd cloned-repo
!ls

Cloning into 'cloned-repo'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 106 (delta 44), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (106/106), 1.69 MiB | 21.67 MiB/s, done.
Resolving deltas: 100% (44/44), done.
/content/cloned-repo
_config.yml  documentations  README.md	week2  week4  week5


In [26]:
iris = np.genfromtxt('/content/cloned-repo/week5/iris.csv' , delimiter= ',' , dtype= 'object' )
print(iris.shape)

(30, 5)


In [27]:
iris_1d = np.genfromtxt('/content/cloned-repo/week5/iris.csv' , delimiter= ',' , dtype= None )
print(iris_1d.shape)

(30,)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


In [28]:
print(iris_1d)

[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, b'Iris-setosa') (5.4, 3.9, 1.7, 0.4, b'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, b'Iris-setosa') (5. , 3.4, 1.5, 0.2, b'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, b'Iris-setosa') (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')
 (7. , 3.2, 4.7, 1.4, b'Iris-versicolor')
 (6.4, 3.2, 4.5, 1.5, b'Iris-versicolor')
 (6.9, 3.1, 4.9, 1.5, b'Iris-versicolor')
 (5.5, 2.3, 4. , 1.3, b'Iris-versicolor')
 (6.5, 2.8, 4.6, 1.5, b'Iris-versicolor')
 (5.7, 2.8, 4.5, 1.3, b'Iris-versicolor')
 (6.3, 3.3, 4.7, 1.6, b'Iris-versicolor')
 (4.9, 2.4, 3.3, 1. , b'Iris-versicolor')
 (6.6, 2.9, 4.6, 1.3, b'Iris-versicolor')
 (5.2, 2.7, 3.9, 1.4, b'Iris-versicolor')
 (6.3, 3.3, 6. , 2.5, b'Iris-virginica')
 (5.8, 2.7, 5.1, 1.9, b'Iris-virginica')
 (7.1, 3. , 5.9, 2.1, b'Iris-virginica')
 (6.3, 2.9, 5.6, 1.8, b'Iris-virginica')
 (6.5, 3. , 5.8, 2.2, b'Iris-virginica')


In [0]:
iris_2d_1 = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d_1)

In [33]:
iris_2d_2 = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float' ,  usecols = [0,1,2,3])
print(iris_2d_2)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]]


In [40]:
sepal_length = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float' ,  usecols = [0])
print(sepal_length)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 7.  6.4 6.9 5.5 6.5 5.7 6.3 4.9
 6.6 5.2 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2]


In [41]:
mean , median , std = np.mean(sepal_length) , np.median(sepal_length) , np.std(sepal_length)
print (mean , median , std)

5.843333333333333 5.75 0.947868954843208


# Chuẩn hóa 
### (a-a.min)/(a.max-a.min)

In [0]:
normal_sl = (sepal_length - sepal_length.min())/(sepal_length.max() - sepal_length.min())

In [43]:
print(normal_sl)

[0.22 0.16 0.09 0.06 0.19 0.31 0.06 0.19 0.   0.16 0.81 0.63 0.78 0.34
 0.66 0.41 0.59 0.16 0.69 0.25 0.59 0.44 0.84 0.59 0.66 1.   0.16 0.91
 0.72 0.88]


# Softmax

In [45]:
def softmax(x):
    e_x = np.exp(x-np.max(x))
    return e_x/e_x.sum()
np.set_printoptions(precision = 4)
print(softmax(sepal_length))

[0.0103 0.0084 0.0069 0.0063 0.0093 0.0139 0.0063 0.0093 0.0051 0.0084
 0.069  0.0379 0.0624 0.0154 0.0418 0.0188 0.0343 0.0084 0.0462 0.0114
 0.0343 0.0208 0.0762 0.0343 0.0418 0.1257 0.0084 0.0931 0.0511 0.0843]


# Missing values , genfromtxt to 2d

In [46]:
iris_2d = np.genfromtxt('/content/cloned-repo/week5/iris.csv', delimiter = ',' , dtype= 'float')
print(iris_2d.shape)

(30, 5)


In [47]:
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]]


In [48]:
print('\n Số phần tử là nan: ' , np.isnan(iris_2d).sum())
index = np.where(np.isnan(iris_2d))
print(index)


 Số phần tử là nan:  30
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4]))
